---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
  baseurl: "http://edward.delaporte.us.github.io/hugo_gh_blog"
  title: "Edward.Delaporte.us"
  canonifyurls: true
